[package]
name = "raster_runtime_tty"
description = "raster_runtime Module tty"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ray-d-song/raster_runtime"
readme = "README.md"

[lib]
name = "raster_runtime_tty"
path = "src/lib.rs"

[dependencies]
raster_runtime_buffer = { version = "0.1.0", path = "../raster_runtime_buffer" }
raster_runtime_context = { version = "0.1.0", path = "../../libs/raster_runtime_context" }
raster_runtime_events = { version = "0.1.0", path = "../raster_runtime_events" }
raster_runtime_utils = { version = "0.1.0", path = "../../libs/raster_runtime_utils", default-features = false }
rquickjs = { version = "=0.12.1", features = ["std"], default-features = false }
libc = { version = "0.2", default-features = false }
crossterm = { version = "0.29", features = ["events", "windows"], default-features = false }
tokio = { version = "1", features = ["io-util", "io-std", "sync", "macros", "rt"], default-features = false }
tracing = { version = "0.1", default-features = false }

[dev-dependencies]
raster_runtime_test = { path = "../../libs/raster_runtime_test" }
tokio = { version = "1", features = ["test-util", "macros", "rt"], default-features = false }
