[package]
name = "raster_runtime_abort"
description = "raster_runtime Module abort"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ray-d-song/raster_runtime"

[lib]
name = "raster_runtime_abort"
path = "src/lib.rs"

[features]
default = ["sleep-timers"]

sleep-timers = ["raster_runtime_timers"]
sleep-tokio = ["tokio"]

[dependencies]
raster_runtime_async_hooks = { version = "0.1.0", path = "../raster_runtime_async_hooks" }
raster_runtime_exceptions = { version = "0.1.0", path = "../raster_runtime_exceptions" }
raster_runtime_events = { version = "0.1.0", path = "../raster_runtime_events" }
raster_runtime_utils = { version = "0.1.0", path = "../../libs/raster_runtime_utils", default-features = false }
rquickjs = { version = "=0.12.1", default-features = false }

# Optional
raster_runtime_timers = { version = "0.1.0", path = "../raster_runtime_timers", optional = true }
tokio = { version = "1", features = [
    "time",
], default-features = false, optional = true }

[dev-dependencies]
raster_runtime_test = { path = "../../libs/raster_runtime_test" }
tokio = { version = "1", features = ["test-util"], default-features = false }
