[package]
name = "raster_runtime_util"
description = "raster_runtime Module util"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ray-d-song/raster_runtime"
readme = "README.md"

[lib]
name = "raster_runtime_util"
path = "src/lib.rs"

[dependencies]
raster_runtime_context = { version = "0.1.0", path = "../../libs/raster_runtime_context" }
raster_runtime_encoding = { version = "0.1.0", path = "../../libs/raster_runtime_encoding" }
raster_runtime_logging = { version = "0.1.0", path = "../../libs/raster_runtime_logging" }
raster_runtime_utils = { version = "0.1.0", path = "../../libs/raster_runtime_utils", default-features = false }
rquickjs = { version = "=0.12.1", default-features = false }
unicode-width = { version = "0.2", default-features = false }

[dev-dependencies]
raster_runtime_test = { path = "../../libs/raster_runtime_test" }
rquickjs = { version = "=0.12.1", features = ["futures"], default-features = false }
tokio = { version = "1", features = ["macros", "rt"], default-features = false }
