[package]
name = "raster_runtime_test"
description = "raster_runtime test helpers"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ray-d-song/raster_runtime"

[lib]
name = "raster_runtime_test"
path = "src/lib.rs"

[dependencies]
rquickjs = { version = "=0.12.1", features = [
  "futures",
  "loader",
  "parallel",
], default-features = false }
tokio = { version = "1", features = ["fs"], default-features = false }
uuid = { version = "1", features = ["v4"], default-features = false }
