[package]
name = "raster_runtime_hooking"
description = "raster_runtime hooking helpers"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ray-d-song/raster_runtime"

[lib]
name = "raster_runtime_hooking"
path = "src/lib.rs"

[dependencies]
raster_runtime_utils = { version = "0.1.0", path = "../../libs/raster_runtime_utils", default-features = false }
once_cell = { version = "1", features = ["std"], default-features = false }
rquickjs = { version = "=0.12.1", default-features = false }
