[package]
name = "raster_runtime_net"
description = "raster_runtime Module net"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ray-d-song/raster_runtime"
readme = "README.md"

[lib]
name = "raster_runtime_net"
path = "src/lib.rs"

[dependencies]
itoa = { version = "1", default-features = false }
raster_runtime_buffer = { version = "0.1.0", path = "../raster_runtime_buffer" }
raster_runtime_context = { version = "0.1.0", path = "../../libs/raster_runtime_context" }
raster_runtime_events = { version = "0.1.0", path = "../raster_runtime_events" }
raster_runtime_stream = { version = "0.1.0", path = "../raster_runtime_stream" }
raster_runtime_utils = { version = "0.1.0", path = "../../libs/raster_runtime_utils", default-features = false }
rquickjs = { version = "=0.12.1", default-features = false }
socket2 = { version = "0.6", default-features = false }
tokio = { version = "1", features = ["io-util", "macros", "net", "rt", "time"], default-features = false }
tracing = { version = "0.1", default-features = false }

[dev-dependencies]
raster_runtime_test = { path = "../../libs/raster_runtime_test" }
rand = { version = "0.10.1", features = ["alloc"], default-features = false }
