[package]
name = "raster_runtime_exceptions"
description = "raster_runtime Module exception"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ray-d-song/raster_runtime"

[lib]
name = "raster_runtime_exceptions"
path = "src/lib.rs"

[dependencies]
rquickjs = { version = "=0.12.1", default-features = false }
raster_runtime_utils = { version = "0.1.0", path = "../../libs/raster_runtime_utils", default-features = false }
