[package]
name = "raster_runtime_string_decoder"
description = "raster_runtime Module string_decoder"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ray-d-song/raster_runtime"
readme = "README.md"

[lib]
name = "raster_runtime_string_decoder"
path = "src/lib.rs"

[dependencies]
raster_runtime_buffer = { version = "0.1.0", path = "../raster_runtime_buffer" }
raster_runtime_encoding = { version = "0.1.0", path = "../../libs/raster_runtime_encoding" }
raster_runtime_utils = { version = "0.1.0", path = "../../libs/raster_runtime_utils", default-features = false }
rquickjs = { version = "=0.12.1", default-features = false }

[dev-dependencies]
raster_runtime_test = { path = "../../libs/raster_runtime_test" }
tokio = { version = "1", features = ["test-util"], default-features = false }
