[package]
name = "raster_runtime_build"
description = "raster_runtime build helpers"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/ray-d-song/raster_runtime"

[lib]
name = "raster_runtime_build"
path = "src/lib.rs"

[dependencies]
rustc_version = { version = "0.4", default-features = false }
